const fs = require('fs');
const path = require('path');
const vm = require('vm');

const dataPath = path.join(__dirname, 'data.js');
const sqlPath = path.join(__dirname, 'migration.sql');

function loadCaseData(filePath) {
    if (!fs.existsSync(filePath)) {
        throw new Error(`No se encontró ${filePath}. Ejecuta primero el build.`);
    }

    const content = fs.readFileSync(filePath, 'utf8');
    const sandbox = {};
    vm.createContext(sandbox);
    vm.runInContext(`${content}\nthis.__CASE_DATA__ = CASE_DATA;`, sandbox);
    return sandbox.__CASE_DATA__;
}

function sqlEscape(value) {
    return String(value || '').replace(/'/g, "''");
}

function sqlText(value) {
    if (value === null || value === undefined) return 'NULL';
    return `'${sqlEscape(value)}'`;
}

function sqlNumber(value) {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? String(parsed) : 'NULL';
}

function buildHechoToCapituloMap(capitulos) {
    const mapping = {};
    (capitulos || []).forEach(capitulo => {
        (capitulo.hechos || []).forEach(hechoId => {
            mapping[hechoId] = capitulo.id;
        });
    });
    return mapping;
}

function buildDeleteByIds(tableName, columnName, ids) {
    const cleanIds = (ids || []).filter(Boolean);
    if (!cleanIds.length) return null;
    return `DELETE FROM public.${tableName} WHERE ${columnName} IN (${cleanIds.map(sqlText).join(', ')});`;
}

function main() {
    const CASE_DATA = loadCaseData(dataPath);
    const sqlStatements = [
        '-- Auto-generated by src/scripts/generate-sql.js',
        '-- Snapshot canónico local para sincronización idempotente con Supabase',
        'BEGIN;'
    ];

    const capitulos = CASE_DATA.capitulos || [];
    const hechos = CASE_DATA.hechos || {};
    const pruebasMeta = CASE_DATA.pruebas_meta || CASE_DATA.pruebas_catalogo || {};
    const archivosCrudos = CASE_DATA.archivos_crudos || [];
    const hechoACapitulo = buildHechoToCapituloMap(capitulos);
    const canonicalFactIds = Object.keys(hechos);

    capitulos.forEach((capitulo, index) => {
        sqlStatements.push(`INSERT INTO public.capitulos (id, numero, titulo, orden) VALUES (${sqlText(capitulo.id)}, ${sqlText(capitulo.numero)}, ${sqlText(capitulo.titulo)}, ${sqlNumber(index + 1)}) ON CONFLICT (id) DO UPDATE SET numero = EXCLUDED.numero, titulo = EXCLUDED.titulo, orden = EXCLUDED.orden;`);
    });

    Object.entries(hechos).forEach(([hechoId, hecho]) => {
        sqlStatements.push(`INSERT INTO public.hechos (id, numero, ordinal, capitulo_id, resumen, texto_completo, texto_completo_html, titulo_corto, nota_abogado, orden_documento, source_key) VALUES (${sqlText(hechoId)}, ${sqlNumber(hecho.numero)}, ${sqlText(hecho.ordinal)}, ${sqlText(hechoACapitulo[hechoId] || hecho.capitulo_id || null)}, ${sqlText(hecho.resumen)}, ${sqlText(hecho.texto_completo)}, ${sqlText(hecho.texto_completo_html)}, ${sqlText(hecho.titulo_corto)}, ${sqlText(hecho.nota_abogado)}, ${sqlNumber(hecho.orden_documento)}, ${sqlText(hecho.source_key)}) ON CONFLICT (id) DO UPDATE SET numero = EXCLUDED.numero, ordinal = EXCLUDED.ordinal, capitulo_id = EXCLUDED.capitulo_id, resumen = EXCLUDED.resumen, texto_completo = EXCLUDED.texto_completo, texto_completo_html = EXCLUDED.texto_completo_html, titulo_corto = EXCLUDED.titulo_corto, nota_abogado = EXCLUDED.nota_abogado, orden_documento = EXCLUDED.orden_documento, source_key = EXCLUDED.source_key;`);
    });

    Object.entries(pruebasMeta).forEach(([proofId, proofMeta]) => {
        sqlStatements.push(`INSERT INTO public.pruebas (id, descripcion, tipo, categoria) VALUES (${sqlText(proofId)}, ${sqlText(proofMeta.descripcion)}, ${sqlText(proofMeta.tipo)}, ${sqlText(proofMeta.categoria)}) ON CONFLICT (id) DO UPDATE SET descripcion = EXCLUDED.descripcion, tipo = EXCLUDED.tipo, categoria = EXCLUDED.categoria;`);
    });

    const deleteMappingsSql = buildDeleteByIds('hecho_pruebas', 'hecho_id', canonicalFactIds);
    if (deleteMappingsSql) {
        sqlStatements.push(deleteMappingsSql);
    }

    const deleteFragmentsSql = buildDeleteByIds('fragmentos_clave', 'hecho_id', canonicalFactIds);
    if (deleteFragmentsSql) {
        sqlStatements.push(deleteFragmentsSql);
    }

    Object.entries(hechos).forEach(([hechoId, hecho]) => {
        (hecho.pruebas || []).forEach(proofId => {
            sqlStatements.push(`INSERT INTO public.hecho_pruebas (hecho_id, prueba_id) VALUES (${sqlText(hechoId)}, ${sqlText(proofId)}) ON CONFLICT (hecho_id, prueba_id) DO NOTHING;`);
        });
    });

    Object.entries(hechos).forEach(([hechoId, hecho]) => {
        (hecho.fragmentos_clave || []).forEach(fragmento => {
            sqlStatements.push(`INSERT INTO public.fragmentos_clave (hecho_id, cita, cita_exacta, fuente, linea, fecha, autor, relevancia) VALUES (${sqlText(hechoId)}, ${sqlText(fragmento.cita)}, ${sqlText(fragmento.cita_exacta)}, ${sqlText(fragmento.fuente)}, ${sqlText(fragmento.linea)}, ${sqlText(fragmento.fecha)}, ${sqlText(fragmento.autor)}, ${sqlText(fragmento.relevancia)});`);
        });
    });

    archivosCrudos.forEach(documento => {
        sqlStatements.push(`INSERT INTO public.documentos (nombre, ruta, tamano) VALUES (${sqlText(documento.nombre)}, ${sqlText(documento.ruta)}, ${sqlNumber(documento.tamano)}) ON CONFLICT (nombre) DO UPDATE SET ruta = EXCLUDED.ruta, tamano = EXCLUDED.tamano;`);
    });

    sqlStatements.push('COMMIT;');

    fs.writeFileSync(sqlPath, `${sqlStatements.join('\n')}\n`);
    console.log(`SQL migration generated with ${sqlStatements.length} statements.`);
}

main();
